SFD-3606 Add contract and smoke test to pipeline
nhsd-exeter/dos-postcode-api pull request #26
Opened 2021-11-30 12:29 UTC by daonhs

2021-12-13 07:00 UTC, gwaardenburg commented on Makefile
> +	make run-smoke COGNITO_POSTCODE=$$(make -s project-aws-get-admin-secret | jq .POSTCODE_PASSWORD | tr -d '"')
Should this be password rather than postcode?

2022-01-04 16:25 UTC, daonhs commented on build/automation/lib/docker.mk
> +		up --no-build --detach --remove-orphans
remove

2022-01-04 16:29 UTC, daonhs commented on build/automation/var/profile/dev.mk
> +ACCESS_ID := $(AWS_ACCESS_KEY_ID)
remove

2022-01-04 16:30 UTC, daonhs commented on deployment/stacks/application/base/template/kustomization.yaml
> +      - AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID_TO_REPLACE
remove

2022-01-04 17:16 UTC, ArifNhs submitted a review, later dismissed
Approved

2022-01-04 17:45 UTC, jope1 requested changes

2022-01-04 17:45 UTC, jope1 commented on Makefile
> +		$(PROJECT_DIR)application/src/main/resources/certificate
I don't understand why you needed to remove the first '/' after the PROJECT_DIR variable. This is in a few places

2022-01-04 17:45 UTC, jope1 commented on Makefile
> +	make run-smoke COGNITO_POSTCODE_AUTH=$$(make -s project-aws-get-admin-secret | jq .POSTCODE_PASSWORD | tr -d '"')
Could we set the COGNITO_POSTCODE_AUTH parameter inside the run-smoke make target rather than have it passed through?

2022-01-04 17:45 UTC, jope1 commented on Makefile
> +	make run-contract COGNITO_POSTCODE_AUTH=$$(make -s project-aws-get-admin-secret | jq .POSTCODE_PASSWORD | tr -d '"')
Could we set the COGNITO_POSTCODE_AUTH parameter inside the run-contract make target rather than have it passed through?

2022-01-04 17:45 UTC, jope1 commented on Makefile
> +project-aws-get-admin-secret:
There is already a make target that will do this. Have a look in aws.mk file. Maybe aws-secret-get will do this for you

2022-01-04 17:45 UTC, jope1 commented on build/automation/var/profile/dev.mk
> +SERVER_PORT := 8443
Why can't we run on 443?

2022-01-04 17:45 UTC, jope1 commented on build/automation/var/profile/dev.mk
> +ALLOWED_ORIGINS := *
Why do we need allowed origins set?

2022-01-04 17:45 UTC, jope1 commented on build/automation/var/profile/local.mk
> +CERTIFICATE_DOMAIN := ${CERTIFICATE_DOMAIN}
Should be 'certificate'

2022-01-04 17:45 UTC, jope1 commented on build/automation/var/profile/prod.mk
> +SERVER_PORT := 8443
Why not 443?

2022-01-04 17:45 UTC, jope1 commented on application/pom.xml
> +    </dependency>
Do we need cognitoidp and jwt dependencies now?

2022-01-04 17:45 UTC, jope1 commented on application/src/main/java/uk/nhs/digital/uec/api/config/SecurityConfig.java
> +  public static final String AUTH_URL = "/authentication/login";
Do we need AUTH_URL?

2022-01-04 17:45 UTC, jope1 commented on application/src/main/java/uk/nhs/digital/uec/api/config/SecurityConfig.java
> +            AUTH_URL);
AUTH_URL?

2022-01-04 17:45 UTC, jope1 commented on application/src/main/java/uk/nhs/digital/uec/api/exception/CognitoIdpSecretHashException.java
> +public class CognitoIdpSecretHashException extends RuntimeException {
Do we still need this class?

2022-01-04 17:45 UTC, jope1 commented on application/src/main/resources/application.yml
> +
Do we need the cognito section?

2022-01-10 11:30 UTC, jope1 submitted a review, later dismissed

2022-01-10 11:31 UTC, ArifNhs approved these changes
Approved

2022-01-10 11:33 UTC, jope1 approved these changes

2022-01-10 11:36 UTC, merged