SFD-3983 Create Lambda Alarms
nhsd-exeter/dos-postcode-api pull request #51
Opened 2022-01-27 08:57 UTC by gwaardenburg

2022-02-01 07:54 UTC, jope1 requested changes

2022-02-01 07:54 UTC, jope1 commented on infrastructure/stacks/postcode_etl_sns/postcode_etl_sns.tf
> +  }
Can you please add tags to this resource?

2022-02-01 07:54 UTC, jope1 commented on infrastructure/stacks/postcode_etl_sns/postcode_etl_sns.tf
> +  }
Can you please add tags to this resource?

2022-02-02 09:45 UTC, jope1 submitted a review, later dismissed

2022-02-02 10:59 UTC, ArifNhs approved these changes

2022-02-02 10:59 UTC, merged